# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion/bin/cmake/bin/cmake

# The command to remove a file.
RM = /opt/clion/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yannick/Workspace/EOS_conv_reverb/impl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yannick/Workspace/EOS_conv_reverb/impl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yannick/Workspace/EOS_conv_reverb/impl/CMakeFiles /home/yannick/Workspace/EOS_conv_reverb/impl/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yannick/Workspace/EOS_conv_reverb/impl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named impl

# Build rule for target.
impl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 impl
.PHONY : impl

# fast build rule for target.
impl/fast:
	$(MAKE) -f CMakeFiles/impl.dir/build.make CMakeFiles/impl.dir/build
.PHONY : impl/fast

CPUconvIdentity.o: CPUconvIdentity.cpp.o

.PHONY : CPUconvIdentity.o

# target to build an object file
CPUconvIdentity.cpp.o:
	$(MAKE) -f CMakeFiles/impl.dir/build.make CMakeFiles/impl.dir/CPUconvIdentity.cpp.o
.PHONY : CPUconvIdentity.cpp.o

CPUconvIdentity.i: CPUconvIdentity.cpp.i

.PHONY : CPUconvIdentity.i

# target to preprocess a source file
CPUconvIdentity.cpp.i:
	$(MAKE) -f CMakeFiles/impl.dir/build.make CMakeFiles/impl.dir/CPUconvIdentity.cpp.i
.PHONY : CPUconvIdentity.cpp.i

CPUconvIdentity.s: CPUconvIdentity.cpp.s

.PHONY : CPUconvIdentity.s

# target to generate assembly for a file
CPUconvIdentity.cpp.s:
	$(MAKE) -f CMakeFiles/impl.dir/build.make CMakeFiles/impl.dir/CPUconvIdentity.cpp.s
.PHONY : CPUconvIdentity.cpp.s

CPUconvOAReverb.o: CPUconvOAReverb.cpp.o

.PHONY : CPUconvOAReverb.o

# target to build an object file
CPUconvOAReverb.cpp.o:
	$(MAKE) -f CMakeFiles/impl.dir/build.make CMakeFiles/impl.dir/CPUconvOAReverb.cpp.o
.PHONY : CPUconvOAReverb.cpp.o

CPUconvOAReverb.i: CPUconvOAReverb.cpp.i

.PHONY : CPUconvOAReverb.i

# target to preprocess a source file
CPUconvOAReverb.cpp.i:
	$(MAKE) -f CMakeFiles/impl.dir/build.make CMakeFiles/impl.dir/CPUconvOAReverb.cpp.i
.PHONY : CPUconvOAReverb.cpp.i

CPUconvOAReverb.s: CPUconvOAReverb.cpp.s

.PHONY : CPUconvOAReverb.s

# target to generate assembly for a file
CPUconvOAReverb.cpp.s:
	$(MAKE) -f CMakeFiles/impl.dir/build.make CMakeFiles/impl.dir/CPUconvOAReverb.cpp.s
.PHONY : CPUconvOAReverb.cpp.s

CPUconvSimpleReverb.o: CPUconvSimpleReverb.cpp.o

.PHONY : CPUconvSimpleReverb.o

# target to build an object file
CPUconvSimpleReverb.cpp.o:
	$(MAKE) -f CMakeFiles/impl.dir/build.make CMakeFiles/impl.dir/CPUconvSimpleReverb.cpp.o
.PHONY : CPUconvSimpleReverb.cpp.o

CPUconvSimpleReverb.i: CPUconvSimpleReverb.cpp.i

.PHONY : CPUconvSimpleReverb.i

# target to preprocess a source file
CPUconvSimpleReverb.cpp.i:
	$(MAKE) -f CMakeFiles/impl.dir/build.make CMakeFiles/impl.dir/CPUconvSimpleReverb.cpp.i
.PHONY : CPUconvSimpleReverb.cpp.i

CPUconvSimpleReverb.s: CPUconvSimpleReverb.cpp.s

.PHONY : CPUconvSimpleReverb.s

# target to generate assembly for a file
CPUconvSimpleReverb.cpp.s:
	$(MAKE) -f CMakeFiles/impl.dir/build.make CMakeFiles/impl.dir/CPUconvSimpleReverb.cpp.s
.PHONY : CPUconvSimpleReverb.cpp.s

GPUconvOAReverb.o: GPUconvOAReverb.cpp.o

.PHONY : GPUconvOAReverb.o

# target to build an object file
GPUconvOAReverb.cpp.o:
	$(MAKE) -f CMakeFiles/impl.dir/build.make CMakeFiles/impl.dir/GPUconvOAReverb.cpp.o
.PHONY : GPUconvOAReverb.cpp.o

GPUconvOAReverb.i: GPUconvOAReverb.cpp.i

.PHONY : GPUconvOAReverb.i

# target to preprocess a source file
GPUconvOAReverb.cpp.i:
	$(MAKE) -f CMakeFiles/impl.dir/build.make CMakeFiles/impl.dir/GPUconvOAReverb.cpp.i
.PHONY : GPUconvOAReverb.cpp.i

GPUconvOAReverb.s: GPUconvOAReverb.cpp.s

.PHONY : GPUconvOAReverb.s

# target to generate assembly for a file
GPUconvOAReverb.cpp.s:
	$(MAKE) -f CMakeFiles/impl.dir/build.make CMakeFiles/impl.dir/GPUconvOAReverb.cpp.s
.PHONY : GPUconvOAReverb.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/impl.dir/build.make CMakeFiles/impl.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/impl.dir/build.make CMakeFiles/impl.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/impl.dir/build.make CMakeFiles/impl.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... impl"
	@echo "... CPUconvIdentity.o"
	@echo "... CPUconvIdentity.i"
	@echo "... CPUconvIdentity.s"
	@echo "... CPUconvOAReverb.o"
	@echo "... CPUconvOAReverb.i"
	@echo "... CPUconvOAReverb.s"
	@echo "... CPUconvSimpleReverb.o"
	@echo "... CPUconvSimpleReverb.i"
	@echo "... CPUconvSimpleReverb.s"
	@echo "... GPUconvOAReverb.o"
	@echo "... GPUconvOAReverb.i"
	@echo "... GPUconvOAReverb.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

